apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: glusterfs-cluster
  spec:
    ports:
    - port: 1
      protocol: TCP
      targetPort: 1
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: null
    name: glusterfs-cluster
  subsets:
  - addresses:
    - ip: 10.1.241.51
    - ip: 10.1.241.52
    - ip: 10.1.241.53
    ports:
    - port: 1
      protocol: TCP
kind: List
metadata: {}
